spring.application.name=serverHealthMonitoring

server.port=${PORT:8081}

# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate Settings
# 'update' automatically creates/updates tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Set retention policy (default to 7 days)
metrics.retention.days=${METRICS_RETENTION_DAYS:7}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 1. STOP Hibernate from printing every single SQL query
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}

# 2. Set the global log level to WARN (hides Spring/Hibernate noise)
logging.level.root=${LOG_LEVEL:WARN}

# 3. Set YOUR project to INFO (shows only your custom messages)
# Replace 'com.project.serverHealthMonitoring' with your actual base package
logging.level.com.project.serverHealthMonitoring=${PROJECT_LOG_LEVEL:INFO}

# 4. Make the log format clean and readable
logging.pattern.console=${LOG_PATTERN:%d{HH:mm:ss} %-5level --- %msg%n}

# Stop the generated security password
spring.main.banner-mode=off
logging.level.org.springframework.security=ERROR

spring.jackson.time-zone=Asia/Kolkata
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata


